language: java
install: true
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update -qq
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.sonar/cache/
before_script:
  - ./gradlew --version -PbintrayUsername=undefined -PbintrayApiKey=undefined
script: ./gradlew clean build -PbintrayUsername=undefined -PbintrayApiKey=undefined
jdk: openjdk11
env: TERM=dumb
